/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgendamentoTelas;

/**
 *
 * @author Gabri
 */
public class CincoRegistrodeRetorno extends javax.swing.JFrame {

    /**
     * Creates new form RegistrodeRetorno
     */
    public CincoRegistrodeRetorno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        txtAdministrativo = new javax.swing.JMenu();
        menuCadastroFuncionarios = new javax.swing.JMenuItem();
        menuCadastroUsuarios = new javax.swing.JMenuItem();
        menuCadastroEspecialidades = new javax.swing.JMenuItem();
        menuCadastroMedicos = new javax.swing.JMenuItem();
        menuCadastroConvenios = new javax.swing.JMenuItem();
        txtAgendamento = new javax.swing.JMenu();
        menuCadastroPaciente = new javax.swing.JMenuItem();
        menuAgendarConsulta = new javax.swing.JMenuItem();
        menuRegistroRetorno = new javax.swing.JMenuItem();
        menuCancelamentoConsulta = new javax.swing.JMenuItem();
        txtAtendimento = new javax.swing.JMenu();
        menuProntuarioPaciente = new javax.swing.JMenuItem();
        menuRegistroAtendimento = new javax.swing.JMenuItem();
        menuReceituario = new javax.swing.JMenuItem();
        menuExames = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        txtAdministrativo1 = new javax.swing.JMenu();
        menuCadastroFuncionarios1 = new javax.swing.JMenuItem();
        menuCadastroUsuarios1 = new javax.swing.JMenuItem();
        menuCadastroEspecialidades1 = new javax.swing.JMenuItem();
        menuCadastroMedicos1 = new javax.swing.JMenuItem();
        menuCadastroConvenios1 = new javax.swing.JMenuItem();
        txtAgendamento1 = new javax.swing.JMenu();
        menuCadastroPaciente1 = new javax.swing.JMenuItem();
        menuAgendarConsulta1 = new javax.swing.JMenuItem();
        menuRegistroRetorno1 = new javax.swing.JMenuItem();
        menuCancelamentoConsulta1 = new javax.swing.JMenuItem();
        txtAtendimento1 = new javax.swing.JMenu();
        menuProntuarioPaciente1 = new javax.swing.JMenuItem();
        menuRegistroAtendimento1 = new javax.swing.JMenuItem();
        menuReceituario1 = new javax.swing.JMenuItem();
        menuExames1 = new javax.swing.JMenuItem();

        txtAdministrativo.setText("Administrativo");

        menuCadastroFuncionarios.setText("Cadastro de Funcionários");
        menuCadastroFuncionarios.setToolTipText("");
        txtAdministrativo.add(menuCadastroFuncionarios);

        menuCadastroUsuarios.setText("Cadastro de Usuários");
        txtAdministrativo.add(menuCadastroUsuarios);

        menuCadastroEspecialidades.setText("Cadastro de Especialidades");
        txtAdministrativo.add(menuCadastroEspecialidades);

        menuCadastroMedicos.setText("Cadastro de Médicos");
        txtAdministrativo.add(menuCadastroMedicos);

        menuCadastroConvenios.setText("Cadastro de Convênios");
        txtAdministrativo.add(menuCadastroConvenios);

        jMenuBar2.add(txtAdministrativo);

        txtAgendamento.setText("Agendamento");

        menuCadastroPaciente.setText("Cadastro de Pacientes");
        menuCadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroPacienteActionPerformed(evt);
            }
        });
        txtAgendamento.add(menuCadastroPaciente);

        menuAgendarConsulta.setText("Agenda de Consulta");
        txtAgendamento.add(menuAgendarConsulta);

        menuRegistroRetorno.setText("Registro de Retorno");
        txtAgendamento.add(menuRegistroRetorno);

        menuCancelamentoConsulta.setText("Cancelamento de Consulta");
        txtAgendamento.add(menuCancelamentoConsulta);

        jMenuBar2.add(txtAgendamento);

        txtAtendimento.setText("Atendimento");

        menuProntuarioPaciente.setText("Prontuário do Paciente");
        txtAtendimento.add(menuProntuarioPaciente);

        menuRegistroAtendimento.setText("Registro de Atendimento");
        txtAtendimento.add(menuRegistroAtendimento);

        menuReceituario.setText("Receituário");
        txtAtendimento.add(menuReceituario);

        menuExames.setText("Exames");
        txtAtendimento.add(menuExames);

        jMenuBar2.add(txtAtendimento);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenuBar2.add(menuSair);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(2, 115, 115));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE RETORNO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("Código  Do Paciente");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("Data");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Hora");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel6.setText("Motivo Do Retorno");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setText("Resultado Dos Exames");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setText("Detalhes Da Última Consulta");

        jTextField5.setToolTipText("");

        jButton1.setText("REGISTRAR");

        jButton2.setText("ALTERAR");

        jButton3.setText("EXCLUIR");

        jButton4.setText("CANCELAR");

        jButton5.setText("SALVAR");

        jButton6.setText("SAIR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jButton2)
                        .addGap(86, 86, 86)
                        .addComponent(jButton3)
                        .addGap(104, 104, 104)
                        .addComponent(jButton4)
                        .addGap(101, 101, 101)
                        .addComponent(jButton5)))
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(198, 198, 198))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addComponent(jButton6))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel6)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(33, 33, 33))
        );

        txtAdministrativo1.setText("Administrativo");

        menuCadastroFuncionarios1.setText("Cadastro de Funcionários");
        menuCadastroFuncionarios1.setToolTipText("");
        txtAdministrativo1.add(menuCadastroFuncionarios1);

        menuCadastroUsuarios1.setText("Cadastro de Usuários");
        txtAdministrativo1.add(menuCadastroUsuarios1);

        menuCadastroEspecialidades1.setText("Cadastro de Especialidades");
        txtAdministrativo1.add(menuCadastroEspecialidades1);

        menuCadastroMedicos1.setText("Cadastro de Médicos");
        txtAdministrativo1.add(menuCadastroMedicos1);

        menuCadastroConvenios1.setText("Cadastro de Convênios");
        txtAdministrativo1.add(menuCadastroConvenios1);

        jMenuBar1.add(txtAdministrativo1);

        txtAgendamento1.setText("Agendamento");

        menuCadastroPaciente1.setText("Cadastro de Pacientes");
        menuCadastroPaciente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroPaciente1ActionPerformed(evt);
            }
        });
        txtAgendamento1.add(menuCadastroPaciente1);

        menuAgendarConsulta1.setText("Agenda de Consulta");
        txtAgendamento1.add(menuAgendarConsulta1);

        menuRegistroRetorno1.setText("Registro de Retorno");
        txtAgendamento1.add(menuRegistroRetorno1);

        menuCancelamentoConsulta1.setText("Cancelamento de Consulta");
        txtAgendamento1.add(menuCancelamentoConsulta1);

        jMenuBar1.add(txtAgendamento1);

        txtAtendimento1.setText("Atendimento");

        menuProntuarioPaciente1.setText("Prontuário do Paciente");
        txtAtendimento1.add(menuProntuarioPaciente1);

        menuRegistroAtendimento1.setText("Registro de Atendimento");
        txtAtendimento1.add(menuRegistroAtendimento1);

        menuReceituario1.setText("Receituário");
        txtAtendimento1.add(menuReceituario1);

        menuExames1.setText("Exames");
        txtAtendimento1.add(menuExames1);

        jMenuBar1.add(txtAtendimento1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroPacienteActionPerformed
        new CadastrodePacientes().setVisible(true);
    }//GEN-LAST:event_menuCadastroPacienteActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // Menu Sair
        this.dispose();
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuCadastroPaciente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroPaciente1ActionPerformed
        new CadastrodePacientes().setVisible(true);
    }//GEN-LAST:event_menuCadastroPaciente1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CincoRegistrodeRetorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CincoRegistrodeRetorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CincoRegistrodeRetorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CincoRegistrodeRetorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CincoRegistrodeRetorno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JMenuItem menuAgendarConsulta;
    private javax.swing.JMenuItem menuAgendarConsulta1;
    private javax.swing.JMenuItem menuCadastroConvenios;
    private javax.swing.JMenuItem menuCadastroConvenios1;
    private javax.swing.JMenuItem menuCadastroEspecialidades;
    private javax.swing.JMenuItem menuCadastroEspecialidades1;
    private javax.swing.JMenuItem menuCadastroFuncionarios;
    private javax.swing.JMenuItem menuCadastroFuncionarios1;
    private javax.swing.JMenuItem menuCadastroMedicos;
    private javax.swing.JMenuItem menuCadastroMedicos1;
    private javax.swing.JMenuItem menuCadastroPaciente;
    private javax.swing.JMenuItem menuCadastroPaciente1;
    private javax.swing.JMenuItem menuCadastroUsuarios;
    private javax.swing.JMenuItem menuCadastroUsuarios1;
    private javax.swing.JMenuItem menuCancelamentoConsulta;
    private javax.swing.JMenuItem menuCancelamentoConsulta1;
    private javax.swing.JMenuItem menuExames;
    private javax.swing.JMenuItem menuExames1;
    private javax.swing.JMenuItem menuProntuarioPaciente;
    private javax.swing.JMenuItem menuProntuarioPaciente1;
    private javax.swing.JMenuItem menuReceituario;
    private javax.swing.JMenuItem menuReceituario1;
    private javax.swing.JMenuItem menuRegistroAtendimento;
    private javax.swing.JMenuItem menuRegistroAtendimento1;
    private javax.swing.JMenuItem menuRegistroRetorno;
    private javax.swing.JMenuItem menuRegistroRetorno1;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu txtAdministrativo;
    private javax.swing.JMenu txtAdministrativo1;
    private javax.swing.JMenu txtAgendamento;
    private javax.swing.JMenu txtAgendamento1;
    private javax.swing.JMenu txtAtendimento;
    private javax.swing.JMenu txtAtendimento1;
    // End of variables declaration//GEN-END:variables
}
